export const BOWLING_DIGITS = [
    // /* 0 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAALklEQVQImWNgYGD4f/nyZThmYGD4zwBnQPHly5dRBeGqYYIoNIpZ2LQj6cC0HQBkolHZ7C9h/QAAAABJRU5ErkJggg==',
//     /* 1 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAJklEQVQImWNgYGD4z8DA8P/y5cv/YWwGmACKIIyDoZICQZglyBgAZMNDA4TnzWUAAAAASUVORK5CYII=',
//     /* 2 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAJUlEQVQImWNgYGD4f/nyZThmYGD4zwBnQDGUz4BdkKB2/ILoGACDm0puYq2M+QAAAABJRU5ErkJggg==',
//     /* 3 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAKElEQVQImWNgYGD4f/nyZThmYGD4zwBnQDGUz4BbEEU7VpU4zUS3HQCgEEV8d2q/dgAAAABJRU5ErkJggg==',
//     /* 4 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAIUlEQVQImWO4fPnyfwYGBlSMLAhn4xRExwzIZiHpIlIQAMA1QwPbg5sEAAAAAElFTkSuQmCC',
//     /* 5 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAKklEQVQImWO4fPnyf3TMcPny5f8MDAyoGKsgAwMDqlaYIDLGaiaUj6kdACMhSm4gJKRkAAAAAElFTkSuQmCC',
//     /* 6 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAKElEQVQImWNgYGD4f/nyZThmYGD4zwBnQPHly5cxBeEqydMO5WPaDgDqM0znpkamPAAAAABJRU5ErkJggg==',
//     /* 7 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAJElEQVQImWO4fPnyf3TMwMDA8B8ZEycIFUAIIglABNEEsAsCAP4GPhFCoMSOAAAAAElFTkSuQmCC',
//     /* 8 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAIklEQVQImWNgYGD4f/nyZThmYGD4zwBnQPHly5dxCNJAOwD2kEzn9JGjQAAAAABJRU5ErkJggg==',
//     /* 9 */     'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAYAAADAp4fuAAAAKklEQVQImWNgYGD4f/nyZThmYGD4zwBnQPHly5dxCKJrhwuSp52BgeE/AAL8TOczDPRuAAAAAElFTkSuQmCC'
    ]
   
   
